### PR TITLE
Added TH

### PR DESCRIPTION
**Pull request by rikoprushka**
Nukes added

### CODE REVIEW

**Comment by Konijima** [comment]
@radiusgreenhill I will push more soon as I have added more stuff to the mod for next update.

**Comment by rikoprushka** [comment]
can't wait for the new features 😊

**Comment by Konijima** [comment]
@radiusgreenhill You can have a look at each translation file in the latest push, I don't think I will add any new text for this update it should be good.

**Comment by rikoprushka** [comment]
Okay, I will proceed accordingly.

**Comment by rikoprushka** [comment]
@Konijima Thai translation completed

**Pull request merged**
